### ISSUE TITLE
package.json-scripts-demo “DEBUG=true rollup -c -w”  Whether or not  ”set DEBUG=true&rollup -c -w“

### ISSUE THREAD

**Issue by loo41** [vaneenige/unswitch#1]
DEBUG 不是内部或外部命令, 也不是可运行程序

**Comment by bjohnso5** [comment]
Based on my [best-effort translation](https://translate.google.com/#auto/en/%E4%B8%8D%E6%98%AF%E5%86%85%E9%83%A8%E6%88%96%E5%A4%96%E9%83%A8%E5%91%BD%E4%BB%A4%2C%20%E4%B9%9F%E4%B8%8D%E6%98%AF%E5%8F%AF%E8%BF%90%E8%A1%8C%E7%A8%8B%E5%BA%8F), it seems you're likely attempting to run the command from Windows. The script style in the `package.json` will only work on UNIX-alike OSes. To make it cross-platform, something like [cross-env](https://www.npmjs.com/package/cross-env) could be used instead

**Comment by vaneenige** [comment]
Thanks @bjohnso5, I've added cross-env (d26f397a07dddeec45684a56490d944d29a26b22) so running the demo should work on all environments now!
