### ISSUE TITLE
Should `axes` work?

### ISSUE THREAD

**Issue by mattdsteele** [vaneenige/unswitch#3]
First off this is such a cool project 👍 

Attempting to use the demo, but I can't get the `axes` to display anything. Running the demo I get `NaN`s:

![image](https://user-images.githubusercontent.com/389077/43612541-4578593c-9672-11e8-911b-e909cfd75526.png)

From what I can tell this line introduces the `NaN`:

https://github.com/vaneenige/unswitch/blob/master/src/index.js#L25

It's referencing `axes[9]`, but at least on my Joy-Con (R), `axes` always returns `[0,0,0,0]`.

Given that it's always an array of size 4, is axes intended to work?

(I'm testing with Firefox on Mac OS, FWIW)

**Comment by mattdsteele** [comment]
Based on this [this test page](http://html5gamepad.com/), it looks like my Joy-Con is triggering buttons 16-19 for up/down/left/right, rather than as an axis.

If this doesn't seem crazy, I can submit a PR to manage these as buttons, let me know what you think!

**Comment by mattdsteele** [comment]
One more note, it looks like both left and right Joy-Cons work this way ^. But a Pro Controller does use the Gamepad's axes (and the D-pad controls buttons 16-19).

**Comment by vaneenige** [comment]
Hey Matt! 

Thank you for reaching out! It's actually good that you mention your browser: the problem actually occurs on both Firefox and Safari.

It's odd that it sees the axes as buttons, but at least it's able to use the same functionality. Combinations like `16-19` and `17-19` also happen for up-left and up-right! 

If you could submit a PR for this that would be much appreciated! I don't own a Pro Controller so I couldn't test it..
