### ISSUE TITLE
Demo website

### ISSUE THREAD

**Issue by juandc** [vaneenige/unswitch#5]
Hey! `unswitch` is awesome but, it could be better if you provide a demo url.

Just use [Github Pages](https://pages.github.com) or [Zeit Now](https://zeit.co/now) :+1: :wink:.

**Comment by vaneenige** [comment]
Hey Juan!

A simple demo can be found on [Codepen](https://codepen.io/cvaneenige/pen/gjdJrP)! I've added this link to the README (672ee099c0ee8d5f917be08b0076d3afc650f73f) too. 🙌

_I'm also planning on making a more fancy demo, stay tuned!_

**Comment by juandc** [comment]
Awesome :muscle:!
